database:
  # Hostname for the MySQL server
  hostname: 'localhost'
  # Port for the MySQL server
  port: '3306'
  # MySQL username
  username: 'admin'
  # MySQL password
  password: 'adminadmin'
  # The name of the MySQL database being used
  name: 'minecraft'
  # Prefix to use for all table names, to prevent table conflict
  table-prefix: 'np_'

