database:
  # Hostname for the MySQL server
  hostname: 'localhost'
  # Port for the MySQL server
  port: '3306'
  # MySQL username
  username: 'admin'
  # MySQL password
  password: 'adminadmin'
  # The name of the MySQL database being used
  name: 'minecraft'
  # Prefix to use for all table names, to prevent table conflict
  table-prefix: 'np_'
actions:
  # Number of warnings a player can have in a session before they are automatically kicked
  # Set to 0 to disable
  warns-until-kick: 0
  # Commands that the player cannot perform while muted, e.g. msg, tell
  disallowed-commands-while-muted:
  - 'msg'
  - 'tell'
